### ISSUE TITLE
Unable to Build mod.cpk on "fresh install"

### ISSUE THREAD

**Issue by camohiddendj** [tge-was-taken/Mod-Compendium#11]
When attempting to build mod.cpk on a fresh copy of ver 1.1.2 the following error occurs...

Unhandled exception occured while building:
Could not find a part of the path 'Output\Persona5\mod.cpk'.
   at System.IO._Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName,
Boolean overwrite, Boolean checkHost)
     at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean
overwrite)
   at
ModCompendiumLibrary.ModSystem.Builders.Persona5ModCpkModBuilder.Build
(VirtualDirectory root, String hostOutputPath, String gameName, Boolean
useCompression, Boolean useExtracted)
   at ModeCompendium.MainWindow.<BuildButton_Click>b_35_0()

If files for 1.1.2 are copied into a directory that already contains the files from 1.1.0 then this error does not happen.

**Comment by gabehxd** [comment]
You need to re-set where the mod.cpk should be put
